//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.01 at 03:17:30 PM CEST 
//


package edu.dedupendnote.domain.xml.zotero;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.dedupendnote.domain.xml.zotero package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.dedupendnote.domain.xml.zotero
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Pages }
     * 
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link Xml }
     * 
     */
    public Xml createXml() {
        return new Xml();
    }

    /**
     * Create an instance of {@link Records }
     * 
     */
    public ZoteroXmlRecords createZoteroXmlRecords() {
        return new ZoteroXmlRecords();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public ZoteroXmlRecord createZoteroXmlRecord() {
        return new ZoteroXmlRecord();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link SourceApp }
     * 
     */
    public SourceApp createSourceApp() {
        return new SourceApp();
    }

    /**
     * Create an instance of {@link ForeignKeys }
     * 
     */
    public ForeignKeys createForeignKeys() {
        return new ForeignKeys();
    }

    /**
     * Create an instance of {@link RefType }
     * 
     */
    public RefType createRefType() {
        return new RefType();
    }

    /**
     * Create an instance of {@link Contributors }
     * 
     */
    public Contributors createContributors() {
        return new Contributors();
    }

    /**
     * Create an instance of {@link Titles }
     * 
     */
    public Titles createTitles() {
        return new Titles();
    }

    /**
     * Create an instance of {@link Periodical }
     * 
     */
    public Periodical createPeriodical() {
        return new Periodical();
    }

    /**
     * Create an instance of {@link ReprintStatus }
     * 
     */
    public ReprintStatus createReprintStatus() {
        return new ReprintStatus();
    }

    /**
     * Create an instance of {@link Dates }
     * 
     */
    public Dates createDates() {
        return new Dates();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Urls }
     * 
     */
    public Urls createUrls() {
        return new Urls();
    }

    /**
     * Create an instance of {@link TertiaryAuthors }
     * 
     */
    public TertiaryAuthors createTertiaryAuthors() {
        return new TertiaryAuthors();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link PubDates }
     * 
     */
    public PubDates createPubDates() {
        return new PubDates();
    }

    /**
     * Create an instance of {@link CopyrightDates }
     * 
     */
    public CopyrightDates createCopyrightDates() {
        return new CopyrightDates();
    }

    /**
     * Create an instance of {@link TranslatedAuthors }
     * 
     */
    public TranslatedAuthors createTranslatedAuthors() {
        return new TranslatedAuthors();
    }

    /**
     * Create an instance of {@link RelatedUrls }
     * 
     */
    public RelatedUrls createRelatedUrls() {
        return new RelatedUrls();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link SecondaryAuthors }
     * 
     */
    public SecondaryAuthors createSecondaryAuthors() {
        return new SecondaryAuthors();
    }

    /**
     * Create an instance of {@link SubsidiaryAuthors }
     * 
     */
    public SubsidiaryAuthors createSubsidiaryAuthors() {
        return new SubsidiaryAuthors();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link WebUrls }
     * 
     */
    public WebUrls createWebUrls() {
        return new WebUrls();
    }

    /**
     * Create an instance of {@link PdfUrls }
     * 
     */
    public PdfUrls createPdfUrls() {
        return new PdfUrls();
    }

    /**
     * Create an instance of {@link TextUrls }
     * 
     */
    public TextUrls createTextUrls() {
        return new TextUrls();
    }

    /**
     * Create an instance of {@link ImageUrls }
     * 
     */
    public ImageUrls createImageUrls() {
        return new ImageUrls();
    }

}
