//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.01 at 03:17:30 PM CEST 
//


package edu.dedupendnote.domain.xml.zotero;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullTitle",
    "abbr1",
    "abbr2",
    "abbr3"
})
@XmlRootElement(name = "periodical")
public class Periodical {

    @XmlElement(name = "full-title")
    protected String fullTitle;
    @XmlElement(name = "abbr-1")
    protected String abbr1;
    @XmlElement(name = "abbr-2")
    protected String abbr2;
    @XmlElement(name = "abbr-3")
    protected String abbr3;

    /**
     * Gets the value of the fullTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullTitle() {
        return fullTitle;
    }

    /**
     * Sets the value of the fullTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullTitle(String value) {
        this.fullTitle = value;
    }

    /**
     * Gets the value of the abbr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr1() {
        return abbr1;
    }

    /**
     * Sets the value of the abbr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr1(String value) {
        this.abbr1 = value;
    }

    /**
     * Gets the value of the abbr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr2() {
        return abbr2;
    }

    /**
     * Sets the value of the abbr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr2(String value) {
        this.abbr2 = value;
    }

    /**
     * Gets the value of the abbr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr3() {
        return abbr3;
    }

    /**
     * Sets the value of the abbr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr3(String value) {
        this.abbr3 = value;
    }

}
