//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.01 at 03:17:30 PM CEST 
//


package edu.dedupendnote.domain.xml.zotero;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "url")
public class Url {

    @XmlAttribute(name = "has-ut")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hasUt;
    @XmlAttribute(name = "ppv-app")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ppvApp;
    @XmlAttribute(name = "ppv-ref")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ppvRef;
    @XmlAttribute(name = "ppv-ut")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ppvUt;
    @XmlValue
    protected String value;

    /**
     * Gets the value of the hasUt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasUt() {
        return hasUt;
    }

    /**
     * Sets the value of the hasUt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasUt(String value) {
        this.hasUt = value;
    }

    /**
     * Gets the value of the ppvApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpvApp() {
        return ppvApp;
    }

    /**
     * Sets the value of the ppvApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpvApp(String value) {
        this.ppvApp = value;
    }

    /**
     * Gets the value of the ppvRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpvRef() {
        return ppvRef;
    }

    /**
     * Sets the value of the ppvRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpvRef(String value) {
        this.ppvRef = value;
    }

    /**
     * Gets the value of the ppvUt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPpvUt() {
        return ppvUt;
    }

    /**
     * Sets the value of the ppvUt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPpvUt(String value) {
        this.ppvUt = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getvalue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setvalue(String value) {
        this.value = value;
    }

}
