//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.01 at 03:17:30 PM CEST 
//


package edu.dedupendnote.domain.xml.zotero;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "database",
    "sourceApp",
    "recNumber",
    "foreignKeys",
    "refType",
    "contributors",
    "authAddress",
    "authAffiliaton",
    "titles",
    "periodical",
    "pages",
    "volume",
    "number",
    "issue",
    "secondaryVolume",
    "secondaryIssue",
    "numVols",
    "edition",
    "section",
    "reprintEdition",
    "reprintStatus",
    "keywords",
    "dates",
    "pubLocation",
    "publisher",
    "origPub",
    "isbn",
    "accessionNum",
    "callNum",
    "reportId",
    "coden",
    "electronicResourceNum",
    "_abstract",
    "label",
    "image",
    "caption",
    "notes",
    "researchNotes",
    "workType",
    "reviewedItem",
    "availability",
    "remoteSource",
    "meetingPlace",
    "workLocation",
    "workExtent",
    "packMethod",
    "size",
    "reproRatio",
    "remoteDatabaseName",
    "remoteDatabaseProvider",
    "language",
    "urls",
    "accessDate",
    "modifiedDate",
    "custom1",
    "custom2",
    "custom3",
    "custom4",
    "custom5",
    "custom6",
    "custom7",
    "misc1",
    "misc2",
    "misc3"
})
@XmlRootElement(name = "record")
public class ZoteroXmlRecord {

    protected Database database;
    @XmlElement(name = "source-app")
    protected SourceApp sourceApp;
    @XmlElement(name = "rec-number")
    protected String recNumber;
    @XmlElement(name = "foreign-keys")
    protected ForeignKeys foreignKeys;
    @XmlElement(name = "ref-type")
    protected RefType refType;
    protected Contributors contributors;
    @XmlElement(name = "auth-address")
    protected String authAddress;
    @XmlElement(name = "auth-affiliaton")
    protected String authAffiliaton;
    protected Titles titles;
    protected Periodical periodical;
    protected Pages pages;
    protected String volume;
    protected String number;
    protected String issue;
    @XmlElement(name = "secondary-volume")
    protected String secondaryVolume;
    @XmlElement(name = "secondary-issue")
    protected String secondaryIssue;
    @XmlElement(name = "num-vols")
    protected String numVols;
    protected String edition;
    protected String section;
    @XmlElement(name = "reprint-edition")
    protected String reprintEdition;
    @XmlElement(name = "reprint-status")
    protected ReprintStatus reprintStatus;
    protected Keywords keywords;
    protected Dates dates;
    @XmlElement(name = "pub-location")
    protected String pubLocation;
    protected String publisher;
    @XmlElement(name = "orig-pub")
    protected String origPub;
    protected String isbn;
    @XmlElement(name = "accession-num")
    protected String accessionNum;
    @XmlElement(name = "call-num")
    protected String callNum;
    @XmlElement(name = "report-id")
    protected String reportId;
    protected String coden;
    @XmlElement(name = "electronic-resource-num")
    protected String electronicResourceNum;
    @XmlElement(name = "abstract")
    protected String _abstract;
    protected String label;
    protected Image image;
    protected String caption;
    protected String notes;
    @XmlElement(name = "research-notes")
    protected String researchNotes;
    @XmlElement(name = "work-type")
    protected String workType;
    @XmlElement(name = "reviewed-item")
    protected String reviewedItem;
    protected String availability;
    @XmlElement(name = "remote-source")
    protected String remoteSource;
    @XmlElement(name = "meeting-place")
    protected String meetingPlace;
    @XmlElement(name = "work-location")
    protected String workLocation;
    @XmlElement(name = "work-extent")
    protected String workExtent;
    @XmlElement(name = "pack-method")
    protected String packMethod;
    protected String size;
    @XmlElement(name = "repro-ratio")
    protected String reproRatio;
    @XmlElement(name = "remote-database-name")
    protected String remoteDatabaseName;
    @XmlElement(name = "remote-database-provider")
    protected String remoteDatabaseProvider;
    protected String language;
    protected Urls urls;
    @XmlElement(name = "access-date")
    protected String accessDate;
    @XmlElement(name = "modified-date")
    protected String modifiedDate;
    protected String custom1;
    protected String custom2;
    protected String custom3;
    protected String custom4;
    protected String custom5;
    protected String custom6;
    protected String custom7;
    protected String misc1;
    protected String misc2;
    protected String misc3;

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link Database }
     *     
     */
    public Database getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link Database }
     *     
     */
    public void setDatabase(Database value) {
        this.database = value;
    }

    /**
     * Gets the value of the sourceApp property.
     * 
     * @return
     *     possible object is
     *     {@link SourceApp }
     *     
     */
    public SourceApp getSourceApp() {
        return sourceApp;
    }

    /**
     * Sets the value of the sourceApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceApp }
     *     
     */
    public void setSourceApp(SourceApp value) {
        this.sourceApp = value;
    }

    /**
     * Gets the value of the recNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecNumber() {
        return recNumber;
    }

    /**
     * Sets the value of the recNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecNumber(String value) {
        this.recNumber = value;
    }

    /**
     * Gets the value of the foreignKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignKeys }
     *     
     */
    public ForeignKeys getForeignKeys() {
        return foreignKeys;
    }

    /**
     * Sets the value of the foreignKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignKeys }
     *     
     */
    public void setForeignKeys(ForeignKeys value) {
        this.foreignKeys = value;
    }

    /**
     * Gets the value of the refType property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getRefType() {
        return refType;
    }

    /**
     * Sets the value of the refType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setRefType(RefType value) {
        this.refType = value;
    }

    /**
     * Gets the value of the contributors property.
     * 
     * @return
     *     possible object is
     *     {@link Contributors }
     *     
     */
    public Contributors getContributors() {
        return contributors;
    }

    /**
     * Sets the value of the contributors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contributors }
     *     
     */
    public void setContributors(Contributors value) {
        this.contributors = value;
    }

    /**
     * Gets the value of the authAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthAddress() {
        return authAddress;
    }

    /**
     * Sets the value of the authAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthAddress(String value) {
        this.authAddress = value;
    }

    /**
     * Gets the value of the authAffiliaton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthAffiliaton() {
        return authAffiliaton;
    }

    /**
     * Sets the value of the authAffiliaton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthAffiliaton(String value) {
        this.authAffiliaton = value;
    }

    /**
     * Gets the value of the titles property.
     * 
     * @return
     *     possible object is
     *     {@link Titles }
     *     
     */
    public Titles getTitles() {
        return titles;
    }

    /**
     * Sets the value of the titles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Titles }
     *     
     */
    public void setTitles(Titles value) {
        this.titles = value;
    }

    /**
     * Gets the value of the periodical property.
     * 
     * @return
     *     possible object is
     *     {@link Periodical }
     *     
     */
    public Periodical getPeriodical() {
        return periodical;
    }

    /**
     * Sets the value of the periodical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periodical }
     *     
     */
    public void setPeriodical(Periodical value) {
        this.periodical = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Pages }
     *     
     */
    public Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pages }
     *     
     */
    public void setPages(Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the secondaryVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryVolume() {
        return secondaryVolume;
    }

    /**
     * Sets the value of the secondaryVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryVolume(String value) {
        this.secondaryVolume = value;
    }

    /**
     * Gets the value of the secondaryIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryIssue() {
        return secondaryIssue;
    }

    /**
     * Sets the value of the secondaryIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryIssue(String value) {
        this.secondaryIssue = value;
    }

    /**
     * Gets the value of the numVols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumVols() {
        return numVols;
    }

    /**
     * Sets the value of the numVols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumVols(String value) {
        this.numVols = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the reprintEdition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReprintEdition() {
        return reprintEdition;
    }

    /**
     * Sets the value of the reprintEdition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReprintEdition(String value) {
        this.reprintEdition = value;
    }

    /**
     * Gets the value of the reprintStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReprintStatus }
     *     
     */
    public ReprintStatus getReprintStatus() {
        return reprintStatus;
    }

    /**
     * Sets the value of the reprintStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReprintStatus }
     *     
     */
    public void setReprintStatus(ReprintStatus value) {
        this.reprintStatus = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Keywords }
     *     
     */
    public Keywords getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *     
     */
    public void setKeywords(Keywords value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link Dates }
     *     
     */
    public Dates getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dates }
     *     
     */
    public void setDates(Dates value) {
        this.dates = value;
    }

    /**
     * Gets the value of the pubLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubLocation() {
        return pubLocation;
    }

    /**
     * Sets the value of the pubLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubLocation(String value) {
        this.pubLocation = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the origPub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigPub() {
        return origPub;
    }

    /**
     * Sets the value of the origPub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigPub(String value) {
        this.origPub = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the accessionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionNum() {
        return accessionNum;
    }

    /**
     * Sets the value of the accessionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionNum(String value) {
        this.accessionNum = value;
    }

    /**
     * Gets the value of the callNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallNum() {
        return callNum;
    }

    /**
     * Sets the value of the callNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallNum(String value) {
        this.callNum = value;
    }

    /**
     * Gets the value of the reportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * Sets the value of the reportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportId(String value) {
        this.reportId = value;
    }

    /**
     * Gets the value of the coden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoden() {
        return coden;
    }

    /**
     * Sets the value of the coden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoden(String value) {
        this.coden = value;
    }

    /**
     * Gets the value of the electronicResourceNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicResourceNum() {
        return electronicResourceNum;
    }

    /**
     * Sets the value of the electronicResourceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicResourceNum(String value) {
        this.electronicResourceNum = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the researchNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResearchNotes() {
        return researchNotes;
    }

    /**
     * Sets the value of the researchNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResearchNotes(String value) {
        this.researchNotes = value;
    }

    /**
     * Gets the value of the workType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * Sets the value of the workType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkType(String value) {
        this.workType = value;
    }

    /**
     * Gets the value of the reviewedItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewedItem() {
        return reviewedItem;
    }

    /**
     * Sets the value of the reviewedItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewedItem(String value) {
        this.reviewedItem = value;
    }

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailability(String value) {
        this.availability = value;
    }

    /**
     * Gets the value of the remoteSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSource() {
        return remoteSource;
    }

    /**
     * Sets the value of the remoteSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSource(String value) {
        this.remoteSource = value;
    }

    /**
     * Gets the value of the meetingPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeetingPlace() {
        return meetingPlace;
    }

    /**
     * Sets the value of the meetingPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeetingPlace(String value) {
        this.meetingPlace = value;
    }

    /**
     * Gets the value of the workLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkLocation() {
        return workLocation;
    }

    /**
     * Sets the value of the workLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkLocation(String value) {
        this.workLocation = value;
    }

    /**
     * Gets the value of the workExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkExtent() {
        return workExtent;
    }

    /**
     * Sets the value of the workExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkExtent(String value) {
        this.workExtent = value;
    }

    /**
     * Gets the value of the packMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackMethod() {
        return packMethod;
    }

    /**
     * Sets the value of the packMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackMethod(String value) {
        this.packMethod = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the reproRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReproRatio() {
        return reproRatio;
    }

    /**
     * Sets the value of the reproRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReproRatio(String value) {
        this.reproRatio = value;
    }

    /**
     * Gets the value of the remoteDatabaseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteDatabaseName() {
        return remoteDatabaseName;
    }

    /**
     * Sets the value of the remoteDatabaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteDatabaseName(String value) {
        this.remoteDatabaseName = value;
    }

    /**
     * Gets the value of the remoteDatabaseProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteDatabaseProvider() {
        return remoteDatabaseProvider;
    }

    /**
     * Sets the value of the remoteDatabaseProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteDatabaseProvider(String value) {
        this.remoteDatabaseProvider = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the urls property.
     * 
     * @return
     *     possible object is
     *     {@link Urls }
     *     
     */
    public Urls getUrls() {
        return urls;
    }

    /**
     * Sets the value of the urls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urls }
     *     
     */
    public void setUrls(Urls value) {
        this.urls = value;
    }

    /**
     * Gets the value of the accessDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessDate() {
        return accessDate;
    }

    /**
     * Sets the value of the accessDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessDate(String value) {
        this.accessDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the custom4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * Sets the value of the custom4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom4(String value) {
        this.custom4 = value;
    }

    /**
     * Gets the value of the custom5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * Sets the value of the custom5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom5(String value) {
        this.custom5 = value;
    }

    /**
     * Gets the value of the custom6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom6() {
        return custom6;
    }

    /**
     * Sets the value of the custom6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom6(String value) {
        this.custom6 = value;
    }

    /**
     * Gets the value of the custom7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom7() {
        return custom7;
    }

    /**
     * Sets the value of the custom7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom7(String value) {
        this.custom7 = value;
    }

    /**
     * Gets the value of the misc1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisc1() {
        return misc1;
    }

    /**
     * Sets the value of the misc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisc1(String value) {
        this.misc1 = value;
    }

    /**
     * Gets the value of the misc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisc2() {
        return misc2;
    }

    /**
     * Sets the value of the misc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisc2(String value) {
        this.misc2 = value;
    }

    /**
     * Gets the value of the misc3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisc3() {
        return misc3;
    }

    /**
     * Sets the value of the misc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisc3(String value) {
        this.misc3 = value;
    }

}
