spring.thymeleaf.cache                  = false

logging.file.name                       = dedupendnote_tests.log
logging.file.path                       = ./logs
logging.level.ch.qos.logback            = info
logging.level.edu.dedupendnote.services = info

baseDir                                 = ${user.home}/dedupendnote_files