//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.24 at 01:53:14 PM CET 
//


package edu.dedupendnote.domain.xml.endnote;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "year",
    "pubDates",
    "copyrightDates"
})
@XmlRootElement(name = "dates")
public class Dates {

    protected Year year;
    @XmlElement(name = "pub-dates")
    protected PubDates pubDates;
    @XmlElement(name = "copyright-dates")
    protected CopyrightDates copyrightDates;

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the pubDates property.
     * 
     * @return
     *     possible object is
     *     {@link PubDates }
     *     
     */
    public PubDates getPubDates() {
        return pubDates;
    }

    /**
     * Sets the value of the pubDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubDates }
     *     
     */
    public void setPubDates(PubDates value) {
        this.pubDates = value;
    }

    /**
     * Gets the value of the copyrightDates property.
     * 
     * @return
     *     possible object is
     *     {@link CopyrightDates }
     *     
     */
    public CopyrightDates getCopyrightDates() {
        return copyrightDates;
    }

    /**
     * Sets the value of the copyrightDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopyrightDates }
     *     
     */
    public void setCopyrightDates(CopyrightDates value) {
        this.copyrightDates = value;
    }

}
